name: rich-text
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.8
  - cudatoolkit=11.7.0
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision=0.14.1
  - numpy=1.24.3
  - pip:
    - diffusers==0.18.2
    - accelerate==0.22.0
    - invisible-watermark==0.2.0
    - safetensors==0.3.2
    - seaborn==0.12.2
    - transformers==4.27.0
    - gradio==3.24.1
    - einops==0.6.1
    - imageio==2.31.1
    - scikit-image==0.21.0
    - scikit-learn==0.24.1
